### ISSUE TITLE
Error: can't find file 'html5'

### ISSUE THREAD

**Issue by jonian** [naqvis/crystal-html5#3]
Hi, I'm getting the error below when trying to use this shard.

```bash
 2 | require "html5"
     ^
Error: can't find file 'html5'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
```

If i use `require "html"`, since the main file is `html.cr`, I get:

```bash
 12 | HTML5.parse(str)
      ^
Error: undefined constant HTML5

Did you mean 'HTML'?
```

If I use `HTML.parse`, I get:

```bash
 12 | HTML.parse(str)
             ^----
Error: undefined method 'parse' for HTML:Module
```

Maybe I'm doing something wrong. I don't have any experience with crystal.  
The only way for this to work is to rename `html.cr` to `html5.cr`.

**Comment by naqvis** [comment]
Thanks @jonian . I've fixed this naming issue and uploaded latest version.

**Comment by jonian** [comment]
Thanks for the quick response @naqvis!
