### ISSUE TITLE
Syntax error in specs

### ISSUE THREAD

**Issue by jwoertink** [naqvis/crystal-html5#8]
https://github.com/naqvis/crystal-html5/blob/990093eca8d3b2fd394a6712ee64e42888668448/spec/token_spec.cr#L546

I accidentally ran `crystal tool format` without specifying which directories, and it ran on my `lib/` dir :joy:  It then threw this error

> syntax error in '././lib/html5/spec/token_spec.cr:546:7': can't use 'key: value' syntax in a hash literal

So I just wanted to pass that along :smile:

**Comment by naqvis** [comment]
Thanks @jwoertink. Interesting enough, this typo was working previously 😃 .  I'll fix this.
